export const INDUSTRIES = [
  'Photography',
  'UI/UX Design',
  'Graphic Design',
  'Motion Graphics',
  'Illustration',
  'Web Development',
  'Backend Development',
  'Mobile Development',
  'Content Writing',
  'Copywriting',
  'Video Editing',
  'Social Media',
  'Marketing & Ads',
  'Music Production',
  'Data Analysis',
  'Consulting',
  'Other',
] as const;
